services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcnodelds-app
    container_name: mcnodelds-app
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
    networks:
      - mcnodelds-network

  postgres:
    image: postgres:latest
    container_name: mcnodelds-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mcnodelds
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - mcnodelds-network

volumes:
  postgres-data:

networks:
  mcnodelds-network:
    driver: bridge
